/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HeaderLayoutRouteImport } from './routes/_headerLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogCreateRouteImport } from './routes/blog_.create'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as HeaderLayoutTestRouteImport } from './routes/_headerLayout/test'
import { Route as HeaderLayoutDocumentRouteImport } from './routes/_headerLayout/document'
import { Route as HeaderLayoutComponentsRouteImport } from './routes/_headerLayout/components'
import { Route as HeaderLayoutAboutRouteImport } from './routes/_headerLayout/about'
import { Route as BlogSlugEditRouteImport } from './routes/blog/$slug.edit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutRoute = HeaderLayoutRouteImport.update({
  id: '/_headerLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCreateRoute = BlogCreateRouteImport.update({
  id: '/blog_/create',
  path: '/blog/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutTestRoute = HeaderLayoutTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutDocumentRoute = HeaderLayoutDocumentRouteImport.update({
  id: '/document',
  path: '/document',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutComponentsRoute = HeaderLayoutComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutAboutRoute = HeaderLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const BlogSlugEditRoute = BlogSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BlogSlugRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/about': typeof HeaderLayoutAboutRoute
  '/components': typeof HeaderLayoutComponentsRoute
  '/document': typeof HeaderLayoutDocumentRoute
  '/test': typeof HeaderLayoutTestRoute
  '/blog/$slug': typeof BlogSlugRouteWithChildren
  '/blog/create': typeof BlogCreateRoute
  '/blog': typeof BlogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/blog/$slug/edit': typeof BlogSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/about': typeof HeaderLayoutAboutRoute
  '/components': typeof HeaderLayoutComponentsRoute
  '/document': typeof HeaderLayoutDocumentRoute
  '/test': typeof HeaderLayoutTestRoute
  '/blog/$slug': typeof BlogSlugRouteWithChildren
  '/blog/create': typeof BlogCreateRoute
  '/blog': typeof BlogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/blog/$slug/edit': typeof BlogSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_headerLayout': typeof HeaderLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/_headerLayout/about': typeof HeaderLayoutAboutRoute
  '/_headerLayout/components': typeof HeaderLayoutComponentsRoute
  '/_headerLayout/document': typeof HeaderLayoutDocumentRoute
  '/_headerLayout/test': typeof HeaderLayoutTestRoute
  '/blog/$slug': typeof BlogSlugRouteWithChildren
  '/blog_/create': typeof BlogCreateRoute
  '/blog/': typeof BlogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/blog/$slug/edit': typeof BlogSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sign-up'
    | '/about'
    | '/components'
    | '/document'
    | '/test'
    | '/blog/$slug'
    | '/blog/create'
    | '/blog'
    | '/api/auth/$'
    | '/blog/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sign-up'
    | '/about'
    | '/components'
    | '/document'
    | '/test'
    | '/blog/$slug'
    | '/blog/create'
    | '/blog'
    | '/api/auth/$'
    | '/blog/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/_headerLayout'
    | '/login'
    | '/sign-up'
    | '/_headerLayout/about'
    | '/_headerLayout/components'
    | '/_headerLayout/document'
    | '/_headerLayout/test'
    | '/blog/$slug'
    | '/blog_/create'
    | '/blog/'
    | '/api/auth/$'
    | '/blog/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeaderLayoutRoute: typeof HeaderLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
  BlogSlugRoute: typeof BlogSlugRouteWithChildren
  BlogCreateRoute: typeof BlogCreateRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_headerLayout': {
      id: '/_headerLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HeaderLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/create': {
      id: '/blog_/create'
      path: '/blog/create'
      fullPath: '/blog/create'
      preLoaderRoute: typeof BlogCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_headerLayout/test': {
      id: '/_headerLayout/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof HeaderLayoutTestRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_headerLayout/document': {
      id: '/_headerLayout/document'
      path: '/document'
      fullPath: '/document'
      preLoaderRoute: typeof HeaderLayoutDocumentRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_headerLayout/components': {
      id: '/_headerLayout/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof HeaderLayoutComponentsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_headerLayout/about': {
      id: '/_headerLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HeaderLayoutAboutRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/blog/$slug/edit': {
      id: '/blog/$slug/edit'
      path: '/edit'
      fullPath: '/blog/$slug/edit'
      preLoaderRoute: typeof BlogSlugEditRouteImport
      parentRoute: typeof BlogSlugRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HeaderLayoutRouteChildren {
  HeaderLayoutAboutRoute: typeof HeaderLayoutAboutRoute
  HeaderLayoutComponentsRoute: typeof HeaderLayoutComponentsRoute
  HeaderLayoutDocumentRoute: typeof HeaderLayoutDocumentRoute
  HeaderLayoutTestRoute: typeof HeaderLayoutTestRoute
}

const HeaderLayoutRouteChildren: HeaderLayoutRouteChildren = {
  HeaderLayoutAboutRoute: HeaderLayoutAboutRoute,
  HeaderLayoutComponentsRoute: HeaderLayoutComponentsRoute,
  HeaderLayoutDocumentRoute: HeaderLayoutDocumentRoute,
  HeaderLayoutTestRoute: HeaderLayoutTestRoute,
}

const HeaderLayoutRouteWithChildren = HeaderLayoutRoute._addFileChildren(
  HeaderLayoutRouteChildren,
)

interface BlogSlugRouteChildren {
  BlogSlugEditRoute: typeof BlogSlugEditRoute
}

const BlogSlugRouteChildren: BlogSlugRouteChildren = {
  BlogSlugEditRoute: BlogSlugEditRoute,
}

const BlogSlugRouteWithChildren = BlogSlugRoute._addFileChildren(
  BlogSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeaderLayoutRoute: HeaderLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
  BlogSlugRoute: BlogSlugRouteWithChildren,
  BlogCreateRoute: BlogCreateRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
